// frontend/src/App.tsx
import './App.css'
import { ContainersComponent } from './components/Containers'
import { LoginComponent } from './components/Login'
import { Sidebar } from './components/Sidebar'
import { TerminalComponent } from './components/Terminal'

function App() {

  return (
    <>
      <div className="flex h-screen bg-gray-800 text-gray-200">
        <Sidebar />
        <div className="flex-grow mx-5">
        </div>
      </div>
    </>
  )
}

export default App

// frontend/src/App.vue
<script setup lang="ts">
import Terminal from './components/Terminal.vue'
import Sidebar from './components/Sidebar.vue'
</script>

<template>
  <div class="flex h-screen bg-gray-800 text-gray-200">
    <Sidebar></Sidebar>
    <div class="flex-grow mx-5">
      <Terminal url="ws://127.0.0.1:8080/console/ws" />
    </div>
  </div>
</template>

<style scoped>
</style>
